README.md

I have added a Discord invite link to the README file so that users who find the project in github can also join the server.

Add Discord invite link to README

---

server/index.js

Corrected cors origin domain name to .org from .com in server/index.js file  #113

---

server/.env.example

Fixed issue [#85 ](https://github.com/lugenx/ecohabit/issues/85)

Added .env.example file for server #85

---

README.md

closes #7 
- Added all the social icons of the contributors with their social link.

" social " section in readme file updated.

---

README.md

Fixed issue https://github.com/lugenx/ecohabit/issues/120

Updated guidelines in Contribute section in README

---

client/src/App.js

As was asked in issue #123  to get rid of wrapping div in the App component. I did that. Also changed single quotes on double quotes because of my prettier extension

Got rid of div in App.js

---

client/src/components/HabitCard/HabitCard.js
client/src/pages/Homepage.js
server/src/controller/habitController.js
server/src/routes/habitRoutes.js

Added getAll to habit controller/routes and dispayed list of users habits on homepage

---

server/src/controller/habitController.js

issue: #144 
Added error handlers to updateHabit, deleteHabit, and getHabit controllers.

Added error handlers to habit controllers

---

client/src/components/ResponsiveAppBar/ResponsiveAppBar.js
client/src/components/Routes.js
client/src/pages/ProfilePage.js

I was thinking of putting the Box with the form on lines 178-255 in a separate component to clean the Profile page up a bit more. Do you want to handle this now, or later when we revisit?

Update user profile using placeholder data, a form to edit info, and route to profile page

---

client/src/components/Recycle/Recycle.js

fixed errors on Recycle.js in the client/components, added an index s…o each child has a 'key' prop & replaced the defaultValue with a nullish coalescing operator. 
I noticed both of these errors in the console and was able to fix them without impacting the functionality

recyclsjs-errors

---

client/src/components/ResponsiveAppBar/ResponsiveAppBar.js

Hi, I have fixed the issue of routing on mobile menu not working. Please review it for further action.

issue #147 routing on mobile menu fixed

---

client/src/components/HabitCard/HabitCard.js

Added the array map index as the key prop to buttons in the CardActions MUI component.

Issue #153: Add key prop to CardActions buttons

---

docs/ideas.md

Added ideas to `docs/ideas.md` for the EcoHabit web application per #14.

Add new product ideas

---

server/src/controller/answerController.js
server/src/controller/earth911controller.js
server/src/controller/habitController.js
server/src/controller/userController.js
server/src/middleware/auth.js

Added HTTP response status codes for all four controllers in the backend
Isuues no: #162

Implement response status codes

---

server/src/controller/answerController.js

added error handling in getAnswer, updateAnswer, and deleteAnswer functions in answerController.js

added error handling in getAnswer, updateAnswer, and deleteAnswer

---

server/index.js
server/src/middleware/errMiddleware.js
server/src/middleware/errorHandler.js

Hi, I have added errMiddleware.js file inside middleware folder and created notFound and errorHandler function. Imported these functions in index file and use them. I have tested making different error, it is working fine. Please check it and inform me if something goes wrong.

error handling middleware function added and used it in index.js

---

README.md

+ Added links to tech stack
+ Added target="_blank" attribute so that it opens in new tab
Thoughts @lugenx ?
Fixes #173

Added links to tech stack

---

client/src/App.js
client/src/components/Alert.js
client/src/components/Login/Login.js
client/src/components/Login/Logout.js
client/src/components/Login/Register.js
client/src/components/ResponsiveAppBar/ResponsiveAppBar.js
client/src/components/Routes.js
client/src/contexts/LoginContext.js
client/src/contexts/RegisterContext.js
client/src/pages/Homepage.js
client/src/pages/ProfilePage.js
client/src/services/auth.js
server/src/controller/userController.js
server/src/models/userModel.js

this pull request implements the authentication functionality for the application by communicating with the back-end with already created endpoints. the following changes have been made:
- corrected the naming of some variables for consistency
- implemented registration, login, and logout functionality
- added and used Context API for state management.
- added registration success message
- added login failure messages
how to test:
to test the changes, follow these steps:
1. click on the "Sign up" button and fill out the registration form.
2. once you've registered, you should get a success message and be directed to the login page. 
3. try logging in using the credentials you just created.
4. if the login is successful, you should be redirected to the main page. If the login fails, you …

Implement authentication functionality

---

client/src/components/Login/Main.js

Issue #181

---

client/src/components/ResponsiveAppBar/ResponsiveAppBar.js
client/src/lib/browser.js

- [Issue #159](https://github.com/lugenx/ecohabit/issues/159)
- Added `browser.js` file inside `client/src/lib`
- Added custom hook `useAvailableHeight` inside `browser.js`

Add useAvailableHeight custom hook

---

client/src/components/Habit/AdminHabitForm.js
client/src/components/Habit/HabitCard.js
client/src/components/Habit/UserHabitForm.js
client/src/pages/Homepage.js

Add functionality to add and remove habits, habit forms, and organize habit folder

---

README.md

Hello there!
What I addressed in this Pull Request:
- Fixed the typo in the 'Running Backend Node JS Application'
- Added a new step to create the .env file and to paste content from .env.example inside
- Added markdown quotes to make the commands easier to read.
Thanks ;)

Update 'How to run' section of README.md

---

server/src/middleware/errorHandler.js

here is some improvement which i made.
Handle async errors: The errorHandler middleware doesn't handle asynchronous errors properly. To handle async errors, you can wrap the next(err) call in a try/catch block or use a library like express-async-handler to handle async errors automatically.
Use next(err) instead of creating a new error: In the notFound middleware, instead of creating a new error and passing it to next(), you can directly call next() with the error. This will make the error handling flow more consistent.
Use consistent error response format: Update the error response format in the errorHandler middleware to include an error field and an optional stack field only in development mode. This ensures a consistent response format regardless of the environment.

Update errorHandler.js for more quality code

---

client/src/components/Login/Main.js

Fixes issue #183 
Changed Lorem Ipsum on login page to "Spreading awareness through,  sustainable actions."

Fix Issue #183

---

client/src/components/Recycle/LocationCard.js
client/src/components/Recycle/Recycle.js

fixes issue #193 
Description
* Added a isLoading state, that would disable the search button and display a loader, while the data is being fetched.
* Centered all cards that shows the fetched data.
[Screencast from 05-28-2023 05:46:51 PM.webm](https://github.com/lugenx/ecohabit/assets/89346667/2bdd5613-d434-4ba6-b03b-39165fc8c17a)

fix issue #193

---

client/src/contexts/UserContext.js
client/src/pages/ProfilePage.js
server/src/controller/userController.js

This pull request addresses issue #209 
Changes made:
- UserContext now fetches user data based on the token and stores it in the state.
- Added error handling during the fetch process. If an error occurs, it will be stored in the error state.
- The user profile component now displays the fetched user data.
- UserContext now provides the user data, token, and any potential errors to all components in the application.
Please review the changes and provide your feedback.

Implement User Data Fetch and Error Handling in UserContext

---

client/src/components/Routes.js
client/src/index.js
client/src/pages/Demo.js
client/src/pages/Demo/Demo.js

All request was executed.
In the instructions was said: "export this component under client/src/pages/index.js as well. Follow the same format as you see inside that file."
I believe you wanted on client/src/index.js, right?
Thanks

create demo page testing #130 

---

server/src/models/userModel.js

- Changed the `User` model to add `habits` field, which is an array of `ObjectIds` that represent the `habits` selected by the specific user.

Add habits in user model

---

server/src/controller/userController.js
server/src/models/userModel.js
server/src/routes/userRoutes.js

- `addHabit`, `removeHabit` controllers.
- routes for `addHabit`, `removeHabit` controllers.
- `userModel` to validate the email for uniqueness only when it is not being modified/created.

#212 Add backend endpoints for user-specific habits

---

client/src/components/WeekBar.js
client/src/pages/Homepage.js

Added weekbar component for habit tracking progress

---

server/.env.example

[BUGFIX]-#235

---

server/.env.example

Reverts lugenx/ecohabit#237
After merging, i found a typo in URL, I will have to revert it.

Revert "[BUGFIX]-#235"

---

client/src/components/Recycle.js

Fixes : #236
Added API URL from environment variables in Recycle.js

Reference API URL from Environment Variables in Recycle.js Fixes #236

---

client/src/pages/Homepage.js

Refactor Homepage component

---

package-lock.json
server/src/controller/answerController.js
server/src/routes/answerRoutes.js

I have updated the **_getAnswer_** controller to include a check for the presence of a date parameter. If a **_date_** parameter is provided, it will execute the **_getAnswerByDate_** method; otherwise, it will proceed with the previous **_getAnswer_** operation.

added endpoint that will return all the answers of the authenticated user for the given date 

---

client/src/components/HabitCard.js
client/src/components/WeekBar.js
client/src/pages/Homepage.js
server/index.js
server/src/controller/answerController.js

This PR introduces the basic habit-tracking functionality. Users can now select options for their habits and view their progress via a progress bar.

Implement Basic Habit Tracking Feature
